query marketPlaceListings($limit:Int){
  marketplaceListings(first:$limit) {
    nodes {
      app {
        id
        name
        updatedAt
        description
        createdAt
        url
      }
    }
  }
}